name: Latest

on:
  push:
    branches:
      - release/v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.4.0
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
      - run: echo ::set-env name=CURRENT_RELEASE::$(echo ${GITHUB_REF#refs/heads/})
      - run: echo ::set-env name=LATEST_RELEASE::$(node ci/get-latest-release.js)
      - run: yarn
      - run: yarn build
      - run: ./ci/publish-latest-docs.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
