name: Next

on:
  push:
    branches:
      - master

env:
  CURRENT_RELEASE: next
  DOCS_BASE: /docs/release/next/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.4.0
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
      - run: yarn
      - run: yarn build
      - run: ./ci/publish-versioned-docs.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
